name = "dialoguemaker/effect_types"
version = "0.1.0-patch-1"
description = "Typings for the Effect class for the Dialogue Maker."
authors = ["Christian Toney <christian.toney@beastslash.com>"]
repository = "https://github.com/DialogueMaker/effect_types"
license = "GPL-3.0"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
